name: Check Issue Assignee CLA
on:
  push:
    branches:
      - issue#21643-cla
  issues:
    types:
      - assigned
  
permissions: read-all
jobs:
  check-cla:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install Dependencies
        run: npm install googleapis google-auth-library

      - name: Check CLA signature
        id: check-cla
        uses: actions/github-script@v6
        env:
          GCP_SERVICE_ACCOUNT_KEY: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
          SPREADSHEET_ID: '${{ secrets.SPREADSHEET_ID }}'
          USERNAME: '${{ github.event.issue.assignee.login || github.event.assignee.login || '' }}'
        with:
          script: |
            try {
              console.log("Starting CLA verification process");
              
              // Verify USERNAME environment variable
              const username = process.env.USERNAME;
              if (!username) {
                console.log("No username found in the event data. This could be a push event.");
                if (context.eventName === 'push') {
                  console.log("This is a push event, skipping CLA check.");
                  core.setOutput('has-signed-cla', 'true');
                  return;
                } else {
                  throw new Error("Username is empty or undefined");
                }
              }
              
              console.log(`Checking CLA signature for user: ${username}`);
              
              // Load required libraries
              const { google } = require('googleapis');
              const { GoogleAuth } = require('google-auth-library');
              
              // Parse the service account key
              const serviceAccountKey = JSON.parse(process.env.GCP_SERVICE_ACCOUNT_KEY);
              
              // Create auth client using service account
              const auth = new GoogleAuth({
                credentials: serviceAccountKey,
                scopes: ['https://www.googleapis.com/auth/spreadsheets.readonly']
              });
              
              console.log("Authentication setup complete");
              
              // Access Google Sheets API
              console.log("Accessing Google Sheets API...");
              const sheets = google.sheets({ version: 'v4', auth });
              
              // Fetch data from spreadsheet
              console.log(`Fetching data from spreadsheet ID: ${process.env.SPREADSHEET_ID}`);
              const response = await sheets.spreadsheets.values.get({
                spreadsheetId: process.env.SPREADSHEET_ID,
                range: 'Usernames!A:A',
              });
              
              // Check for valid response
              if (!response.data.values) {
                console.log("No values found in spreadsheet");
                core.setOutput('has-signed-cla', 'false');
                return;
              }
              
              console.log(`Found ${response.data.values.length} rows in the spreadsheet`);
              
              // Check if username exists in the spreadsheet
              const lowercaseUsername = username.toLowerCase();
              const hasSignedCla = response.data.values.some(row => 
                row[0] && row[0].toLowerCase() === lowercaseUsername
              );
              
              console.log(`User ${username} has ${hasSignedCla ? '' : 'not '}signed the CLA`);
              core.setOutput('has-signed-cla', hasSignedCla ? 'true' : 'false');
              
            } catch (error) {
              console.error("Error during CLA verification:", error);
              core.warning(`CLA check failed: ${error.message}`);
              // Don't fail the workflow on error, default to allowing the contribution
              core.setOutput('has-signed-cla', 'true');
            }

      - name: Remove assignee and notify if CLA not signed
        if: steps.check-cla.outputs.has-signed-cla == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const assignee = context.payload.assignee;
            if (!issue || !assignee) {
              core.setFailed('Invalid event payload');
              return;
            }
            const linkToCla = '[here](https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up)';

            const commentBody = `Hi @${assignee.login}, you need to sign the CLA before you can get assigned to issues. Follow the instructions ${linkToCla} to get started. I am unassigning you for now, feel free to assign yourself once you have signed the CLA. Thanks!`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: commentBody
            });
            await github.rest.issues.removeAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              assignees: [assignee.login]
            });
            console.log(`Removed assignee ${assignee.login} from issue #${issue.number} due to unsigned CLA`);
            
      - name: Report failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const message = "Failed to check CLA for issue assignee";
            const webhookUrl = process.env.WEBHOOK_URL;
            
            if (webhookUrl) {
              const https = require('https');
              const url = new URL(webhookUrl);
              
              const data = JSON.stringify({
                text: message
              });
              
              const options = {
                hostname: url.hostname,
                path: url.pathname,
                method: 'POST',
                headers: {
                  'Content-Type': 'application/json',
                  'Content-Length': data.length
                }
              };
              
              const req = https.request(options, (res) => {
                console.log(`Webhook notification sent with status code: ${res.statusCode}`);
              });
              
              req.on('error', (error) => {
                console.error('Error sending webhook notification:', error);
              });
              
              req.write(data);
              req.end();
            } else {
              console.log('No webhook URL provided, skipping notification');
            }
        env:
          WEBHOOK_URL: ${{ secrets.BUILD_FAILURE_ROOM_WEBHOOK_URL }}