name: Checking PR description
on:
  pull_request:
    types:
        - opened
        - reopened
        - edited
permissions: {}
jobs:
  check_pr_description:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run PR description check
        uses: actions/github-script@v6
        with:
            script: |
                const prDescription = context.payload.pull_request.body;
                console.log("PR Description:", prDescription);
                const requiredFormat = /^#\s+PR Title\n\n(?:- .+\n)+/;

                if (!prDescription || !requiredFormat.test(prDescription)) {
                    throw new Error("The PR description is missing or does not meet the required format.");
                }
        

      - name: Report failure if PR description is missing
        if: failure()
        uses: ./.github/actions/send-webhook-notification
        with:
          message: "The PR description is missing or does not meet the required format."
          webhook-url: ${{ secrets.BUILD_FAILURE_ROOM_WEBHOOK_URL }}
