name: Checking PR description
on:
  pull_request:
    types:
        - opened
        - reopened
        - edited
permissions: {}
jobs:
  check_pr_description:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run PR description check
        uses: actions/github-script@v6
        env:
          USERNAME: '${{ github.event.pull_request.user.login || github.event.assignee.login }}'
        with:
            script: |
                const prDescription = context.payload.pull_request.body;
                if (!prDescription) {
                    throw new Error("The PR description is missing or does not meet the required format.");
                }
                console.log("PR Description:", prDescription);
                const requiredSections = [
                    '## Overview',
                    '## Essential Checklist',
                    '## Proof that changes are correct',
                    '## PR Pointers'
                ];
                const username = process.env.USERNAME;
                console.log("Username:", username);
                const missingSections = requiredSections.filter(
                    section => !PR_description.includes(section)
                );
                console.log("Missing Sections:", missingSections);
                if (missingSections.length > 0) {
                    const pr = context.payload.pull_request;
                    const comment = "Hi @${username}, can you complete the following:
                    await github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: pr.number,
                        body: comment
                    });
                    await github.rest.pulls.update({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: pr.number,
                        state: 'closed'
                    });
                    throw new Error("The PR description is missing required sections.");
                }
        
      - name: Report failure if PR description is missing
        if: failure()
        uses: ./.github/actions/send-webhook-notification
        with:
          message: "The PR description is missing or does not meet the required format."
          webhook-url: ${{ secrets.BUILD_FAILURE_ROOM_WEBHOOK_URL }}
